name: modern_bottom_nav_bar
description: A modern and customizable bottom navigation bar for Flutter apps.
version: 0.0.1
homepage: https://github.com/yourusername/modern_bottom_nav_bar
repository: https://github.com/yourusername/modern_bottom_nav_bar
issue_tracker: https://github.com/yourusername/modern_bottom_nav_bar/issues

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add other dev dependencies here if necessary

flutter:
  plugin:
    platforms:
      android:
        package: com.example.modern_bottom_nav_bar
        pluginClass: ModernBottomNavBarPlugin
      ios:
        pluginClass: ModernBottomNavBarPlugin

example:
  dependencies:
    modern_bottom_nav_bar:
      path: 
